### ISSUE TITLE
FindOrganizationByName panics when token does not have rights

### ISSUE THREAD

**Issue by antongocode** [influxdata/influxdb-client-go#151]
Using a token that does not have the correct access rights results in a Organization response with zero elements. The go client does not handle this case, tries to return index zero and panics.

```shell
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
testing.tRunner.func1.1(0xa51f40, 0xc00002e420)
	/home/user/.gvm/gos/go1.14.2/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc000154a20)
	/home/user/.gvm/gos/go1.14.2/src/testing/testing.go:943 +0x3f9
panic(0xa51f40, 0xc00002e420)
	/home/user/.gvm/gos/go1.14.2/src/runtime/panic.go:969 +0x166
github.com/influxdata/influxdb-client-go/api.(*organizationsApiImpl).FindOrganizationByName(0xc00012a090, 0xb6aa80, 0xc000126010, 0xa971ec, 0x8, 0x58, 0xab0a99, 0xe)
	/home/user/.gvm/pkgsets/go1.14.2/global/pkg/mod/github.com/influxdata/influxdb-client-go@v1.3.0/api/organizations.go:101 +0x269
```

**Comment by vlastahajek** [comment]
@antongocode, thanks for posting the issue.
