### ISSUE TITLE
Panic in docker container

### ISSUE THREAD

**Issue by SDpower** [influxdata/influxdb-client-go#265]
__Steps to reproduce:__
Build simple project with Docker and run.
**But run normal  will work fine out side the docker**.

```go
## main.go
func main() {
   var wg sync.WaitGroup	
   wg.Add(2)
   go server.CreateInfluxClient()
   go server.CreateInfluxClient()
   wg.Wait()
}
```

```go
##client.go
package server

import (
	"fmt"
	"os"
	"sync"
	"time"

	influxdb2 "github.com/influxdata/influxdb-client-go/v2"
	"github.com/influxdata/influxdb-client-go/v2/api"
)

var (
	FuturesWriteAPI api.WriteAPI
	StockWriteAPI api.WriteAPI
)

func CreateInfluxClient() {
	var wg sync.WaitGroup	
	wg.Add(1)

	token := os.Getenv("INFLUX_TOKEN")
	Fbucket := os.Getenv("INFLUX_BUCKET_FUTURES")
	Sbucket := os.Getenv("INFLUX_BUCKET_STOCKS")
	org := os.Getenv("INFLUX_ORG")
  
	client := influxdb2.NewClient(os.Getenv("INFLUX_HOST"), token)
	FuturesWriteAPI = client.WriteAPI(org, Fbucket)
	StockWriteAPI = client.WriteAPI(org, Sbucket)
	// always close client at the end
	defer client.Close()

	fmt.Print("WriteAPI Ready\n")

//wait some data to write ......
	wg.Wait()
	fmt.Print("WriteAPI End\n")
}
```

__Expected behavior:__
Runing while.

__Actual behavior:__
panic in docker container.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x65f7cb]

goroutine 50 [running]:
net/url.(*URL).ResolveReference(0x0, 0xc00024c120, 0xc00024c120)
	/usr/local/go/src/net/url/url.go:1077 +0x8b
net/url.(*URL).Parse(0x0, 0xcace03, 0x5, 0xd71940, 0xc000220450, 0xc0001b20f0)
	/usr/local/go/src/net/url/url.go:1065 +0x85
github.com/influxdata/influxdb-client-go/v2/internal/write.NewService(0xc00002409b, 0x7, 0xc000030046, 0xe, 0xd7f4a8, 0xc0001d4600, 0xc0001c0730, 0xc0001b20f0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/internal/write/service.go:64 +0xab
github.com/influxdata/influxdb-client-go/v2/api.NewWriteAPI(0xc00002409b, 0x7, 0xc000030046, 0xe, 0xd7f4a8, 0xc0001d4600, 0xc0001c0730, 0xc0001b20f0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/api/write.go:62 +0x8e
github.com/influxdata/influxdb-client-go/v2.(*clientImpl).WriteAPI(0xc00022e180, 0xc00002409b, 0x7, 0xc000030046, 0xe, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/client.go:205 +0x1f4
github.com/sdpower/shioaji-sub/pkg/server.CreateInfluxClient()
	/home/ubuntu/shioaji-sub/pkg/server/influxdb.go:29 +0x1c3
```

__Specifications:__
 - Client Version: influxdb2 "github.com/influxdata/influxdb-client-go/v2"
 - InfluxDB Version: InfluxDB 2.0.7
 - Platform: OSX & Linux with golang

**Comment by vlastahajek** [comment]
@SDpower, could, please, show what value `INFLUX_HOST` contains?

**Comment by SDpower** [comment]
@vlastahajek 
```
PWD=/go/bin
HOME=/root
GOLANG_VERSION=1.16.6
INFLUX_ORG=sdpower
TERM=xterm
SHLVL=1
MQTT_HOST=192.168.0.10
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GOPATH=/go
INFLUX_HOST="http://192.168.0.10:8086"
OLDPWD=/go
_=/usr/bin/env
root@81011434536b:/go/bin# ./project run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x65f7cb]

goroutine 7 [running]:
net/url.(*URL).ResolveReference(0x0, 0xc00015a120, 0xc00015a120)
	/usr/local/go/src/net/url/url.go:1077 +0x8b
net/url.(*URL).Parse(0x0, 0xcace03, 0x5, 0xd71940, 0xc00012e3c0, 0xc0000260c0)
	/usr/local/go/src/net/url/url.go:1065 +0x85
github.com/influxdata/influxdb-client-go/v2/internal/write.NewService(0xc00002606b, 0x7, 0xc00002c046, 0xe, 0xd7f4a8, 0xc0000e8200, 0xc00007c0a0, 0xc0000260c0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/internal/write/service.go:64 +0xab
github.com/influxdata/influxdb-client-go/v2/api.NewWriteAPI(0xc00002606b, 0x7, 0xc00002c046, 0xe, 0xd7f4a8, 0xc0000e8200, 0xc00007c0a0, 0xc0000260c0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/api/write.go:62 +0x8e
github.com/influxdata/influxdb-client-go/v2.(*clientImpl).WriteAPI(0xc00013c180, 0xc00002606b, 0x7, 0xc00002c046, 0xe, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.4.0/client.go:205 +0x1f4
github.com/sdpower/shioaji-sub/pkg/server.CreateInfluxClient()
	/home/ubuntu/shioaji-sub/pkg/server/influxdb.go:29 +0x1c3
```

**Comment by vlastahajek** [comment]
Thanks. The root problem is in `INFLUX_HOST="http://192.168.0.10:8086"`, where the URL is surrounded by double quotes.
And, of course, the secondary problem is that the library shouldn't crash..

**Comment by SDpower** [comment]
After remove it work for me😳. I didn't notice the difference between passer by docker and me.🙇‍♂️
